import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :blog, BlogWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: Blog.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

profile_file_path =
  System.get_env("PROFILE_FILE_PATH") ||
    raise """
    environment variable PROFILE_FILE_PATH is missing.
    """

posts_dir_path =
  System.get_env("POSTS_DIR_PATH") ||
    raise """
    environment variable POSTS_DIR_PATH is missing
    """

thumbnail_dir_path =
  System.get_env("THUMBNAIL_DIR_PATH") ||
    raise """
    environment variable THUMBNAIL_DIR_PATH is missing
    """

# Custom Config
config :blog,
  profile_file_path: profile_file_path,
  posts_dir_path: posts_dir_path,
  thumbnail_dir_path: thumbnail_dir_path
